version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
      time: "12:00"
      timezone: Europe/Moscow
    open-pull-requests-limit: 10
    reviewers:
      - vladimirlukyanov
    labels:
      - dependencies
      - v5
    versioning-strategy: increase
    rebase-strategy: disabled
