blank_issues_enabled: false
contact_links:
  - name: Documentation Issue
    url: https://github.com/nulllogic/16grid/docs
    about: 'For documentation issues, suggest changes on our documentation repository.'