name: BrowserStack
on: [push]
env:
  CI: true
  NODE: 12.x

jobs:
  browserstack:
    runs-on: ubuntu-latest
    if: github.repository == 'nulllogic/16Blocks'

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "${{ env.NODE }}"

      - name: Install npm dependencies
        run: npm i

      - name: Run dist
        run: npm run dist

      - name: Run BrowserStack tests
        run: npm run js-test-cloud
        env:
          BROWSER_STACK_ACCESS_KEY: "${{ secrets.BROWSER_STACK_ACCESS_KEY }}"
          BROWSER_STACK_USERNAME: "${{ secrets.BROWSER_STACK_USERNAME }}"