name: CSS
on: [push, pull_request]
env:
  CI: true
  NODE: 12.x

jobs:
  css:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "${{ env.NODE }}"

      - name: Install npm dependencies
        run: npm i

      - name: Build CSS
        run: npm run css